### PR TITLE
Agent Registry Interface

### PR DESCRIPTION
**Pull request by framedintent**

### CODE REVIEW

**Comment by framedintent** [comment]
@rcondron @alex-sandrk @srt0422 Can I have a review, please?

**Comment by framedintent** [comment]
@rcondron @alex-sandrk @srt0422

**Comment by rcondron** [comment]
Having @bohdan-titan check build and confirm code.

**Comment by framedintent** [comment]
Merged into Lumerin-protocol fork

**Comment by framedintent** [comment]
Merged into Lumerin-protocol fork

**Pull request closed without merging**
