### PR TITLE
Added Nirmaan Dashboard : Backend and Frontend

### PR DESCRIPTION
**Pull request by NirmaanAI**
# Added Nirmaan Dashboard : Backend and Frontend
This pull request adds the Backend and Frontend code for the Nirmaan-Lumerin Dashboard to the existing Lumerin Node Repository and adds a comprehensive and interactive dashboard for Users and Providers to access and visualise essential data from the Node from Models, Agents and Providers.

## Changes Introduced:
- Added backend code with essential files and detailed documentation.
- Added frontend code with essential files and detailed documentation.

## Backend Details
Technology Stack: [Python, FastAPI, web3.py]
### Key Features:
- Detailed API endpoints created that fetch the necessary data from the Lumerin Smart Contracts.
- Complex mappings and relationships established to serve blockchain data in a clean and efficient manner.
- Seamless Integration with our ReactJS backend to create a user-friendly full stack dashboard application.
## Frontend Details
Technology Stack: [ReactJS, Javascript, HTML, CSS]
### Key Features:
- Comprehensive list of Components developed where each component plays a crucial role in bringing the dashboard alive by not only creating a beautiful UI but also adding functionality and interactiveness.
- Essential components and their-subcomponents allow ease of access and correct utilization of data from the backend while maintaining essential structure.
- Seamless Integration with our FastAPI Backend create a user-friendly full stack dashboard application.
## How to Run
Backend: Detailed API Reference and Steps mentioned in `nirmaan-dashboard/nirmaan-dashboard-backend/README.md`
Frontend: Detailed Overview and Steps mentioned in `nirmaan-dashboard/nirmaan-dashboard-frontend/README.md`
### Backend Testing:
- Extensively tested using Postman to ensure all API endpoints function correctly.
- Verified provider authentication, data retrieval, and data manipulation.

### Frontend Testing:
- Tested in conjunction with the backend to ensure seamless integration.
- Verified that the user interface operates as expected and interacts correctly with the backend.

### Local Environment:

- All tests were run locally, and everything operated correctly without issues.

## Dashboard
Screenshot 2024-05-30 174006

Screenshot 2024-05-30 174125

Screenshot 2024-05-30 174413

Screenshot 2024-05-30 174626

### CODE REVIEW

**Comment by rcondron** [comment]
Asking Lachsbagel to jump in and confirm python build.

**Comment by NirmaanAI** [comment]
@LachsBagel happy to help if you are stuck anywhere

**Comment by NirmaanAI** [comment]
@rcondron We have hosted this Dashboard here: https://morpheus-nirmaan.pages.dev/

- To access the Personalised Provider page, you can use this URL below or connect wallet using a Registered Provider address from the testnet contracts : 
https://morpheus-nirmaan.pages.dev/provider?address=0xE07F2b48FB5801F57FCFd6562fDA6185a66AF4C3. 
(This address in the params is a registered provider in the ProviderRegistry Smart Contract so it will show personalized data associated with this provider)

**Comment by rcondron** [comment]
After reviewing the current state of code and web app completeness it was determined that the web app is not sufficiently done enough to be useful for the community at this time.

**Pull request closed without merging**
